// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bommnpdpzmvqufurwwik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbW1ucGRwem12cXVmdXJ3d2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxODg2MzIsImV4cCI6MjA2MTc2NDYzMn0.eZRb_vDDzPYnv2UOaefq7rLnigji9oD7PTQpd_bY5pE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// MOBILE OPTIMIZATION: Enhanced config for mobile browsers
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // MOBILE FIX: Use PKCE flow for better mobile security
    flowType: 'pkce',
    // MOBILE FIX: Detect storage capability safely
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'sb-bommnpdpzmvqufurwwik-auth-token',
    // MOBILE FIX: Auto-refresh tokens before expiry
    autoRefreshToken: true,
    persistSession: true,
    // MOBILE FIX: Detect and handle session presence
    detectSessionInUrl: true
  },
  global: {
    // MOBILE FIX: Longer timeout for slow mobile networks
    headers: {
      'X-Client-Info': 'supabase-js-web-mobile'
    },
    fetch: (url, options = {}) => {
      // MOBILE FIX: Add mobile-friendly timeout
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000); // 15s timeout
      
      return fetch(url, {
        ...options,
        signal: controller.signal
      }).finally(() => clearTimeout(timeoutId));
    }
  },
  realtime: {
    // MOBILE FIX: Throttle realtime events for mobile
    params: {
      eventsPerSecond: 2
    }
  }
});