import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/sections/Footer';
import { Separator } from '@/components/ui/separator';
import { ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col bg-[#f7f7f7]">
      <Navbar isLoggedIn={false} />
      <main className="flex-1 container py-12 max-w-4xl mx-auto">
        <div className="bg-white rounded-2xl shadow-sm p-8 mb-8">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-3xl font-bold mb-3">Privacy Policy</h1>
            <p className="text-muted-foreground mb-8">Last Updated: {new Date().toLocaleDateString()}</p>
            
            <div className="space-y-10">
              <section>
                <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
                <p className="mb-4">
                  Outer Circle ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Outer Circle.
                </p>
                <p>
                  This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                </p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Definitions and Key Terms</h2>
                <p className="mb-4">For this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Cookie:</strong> A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</li>
                  <li><strong>Company:</strong> When this policy mentions "Company," "we," "us," or "our," it refers to Outer Circle that is responsible for your information under this Privacy Policy.</li>
                  <li><strong>Personal Data:</strong> Any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.</li>
                  <li><strong>Service:</strong> Refers to the website and any applications, software, or services offered by Outer Circle.</li>
                  <li><strong>Third-party service:</strong> Refers to advertisers, sponsors, partners, and other third parties that provide content or functionality on our Service.</li>
                  <li><strong>You:</strong> A person or entity that is registered with Outer Circle to use the Service.</li>
                  <li><strong>Sensitive Personal Information:</strong> Information that reveals a consumer's social security number, driver's license number, state identification card, passport number, precise geolocation, racial or ethnic origin, religious or philosophical beliefs, union membership, contents of mail/email/text messages (unless the business is the intended recipient), genetic data, biometric information, health data, or sex life or sexual orientation data.</li>
                </ul>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Information We Collect</h2>
                <p className="mb-4">We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, fill out a form, or use our Service.</p>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Personal Information</h3>
                <p className="mb-4">We may collect the following types of personal information:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Contact information (such as name, email address, mailing address, and phone number)</li>
                  <li>Username and password for account setup</li>
                  <li>Profile information (such as profile picture, location, interests)</li>
                  <li>Payment and billing information</li>
                  <li>Information about your activity on our platform</li>
                  <li>Device information and IP address</li>
                  <li>Location data</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Automatically Collected Information</h3>
                <p>When you use our Service, we may automatically collect certain information about your device and usage of the Service. This might include your IP address, device type, unique device identification numbers, browser type, broad geographic location, and other technical information.</p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">How We Use Your Information</h2>
                <p className="mb-4">We use the information we collect in various ways, including to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Provide, operate, and maintain our Service</li>
                  <li>Improve, personalize, and expand our Service</li>
                  <li>Understand and analyze how you use our Service</li>
                  <li>Develop new products, services, features, and functionality</li>
                  <li>Communicate with you, either directly or through one of our partners, for customer service, updates and other information relating to the Service, and for marketing and promotional purposes</li>
                  <li>Process your transactions</li>
                  <li>Send you text messages and push notifications</li>
                  <li>Find and prevent fraud</li>
                  <li>For compliance purposes, including enforcing our Terms of Service, or other legal rights, or as may be required by applicable laws and regulations</li>
                </ul>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">UK GDPR Compliance</h2>
                <p className="mb-4">For users in the United Kingdom, we comply with the UK General Data Protection Regulation (UK GDPR) which regulates how personal data of UK residents is processed and handled.</p>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Data Controller</h3>
                <p className="mb-4">Outer Circle serves as the data controller for personal information collected from users in the UK. We are responsible for determining the purposes and means of processing your personal data.</p>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Lawful Basis for Processing</h3>
                <p className="mb-4">Under the UK GDPR, we process your personal data on the following lawful bases:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Consent</strong> - Where you have given clear consent for us to process your personal data for a specific purpose.</li>
                  <li><strong>Contract</strong> - Where processing is necessary for the performance of a contract with you.</li>
                  <li><strong>Legal Obligation</strong> - Where processing is necessary for compliance with a legal obligation to which we are subject.</li>
                  <li><strong>Legitimate Interests</strong> - Where processing is necessary for the legitimate interests pursued by us or a third party, except where such interests are overridden by your interests or fundamental rights.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">International Transfers</h3>
                <p className="mb-4">If we transfer your personal data outside the UK, we will ensure appropriate safeguards are in place to protect your information in accordance with UK GDPR requirements, such as standard contractual clauses or adequacy decisions.</p>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Your UK GDPR Rights</h3>
                <p className="mb-4">Under the UK GDPR, you have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to be informed</strong> - About how we collect and use your personal data.</li>
                  <li><strong>Right of access</strong> - To request a copy of the personal data we hold about you.</li>
                  <li><strong>Right to rectification</strong> - To have inaccurate personal data rectified or completed if it is incomplete.</li>
                  <li><strong>Right to erasure</strong> - To request the deletion or removal of your personal data where there is no compelling reason for its continued processing.</li>
                  <li><strong>Right to restrict processing</strong> - To request that we restrict or block the processing of your personal data.</li>
                  <li><strong>Right to data portability</strong> - To request your personal data in a structured, commonly used and machine-readable format.</li>
                  <li><strong>Right to object</strong> - To processing based on legitimate interests or direct marketing.</li>
                  <li><strong>Rights related to automated decision making and profiling</strong> - Safeguards against the risk that a potentially damaging decision is taken without human intervention.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">UK Data Protection Authority</h3>
                <p className="mb-4">If you are not satisfied with our response to any request you make, or if you believe your personal data is being processed in a way that is not in accordance with the law, you have the right to lodge a complaint with the Information Commissioner's Office (ICO), the UK supervisory authority for data protection issues.</p>
                <p className="mt-4">To exercise any of your UK GDPR rights, please contact us at info@outercircl.com.</p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">GDPR Privacy Rights (For European Union Residents)</h2>
                <p className="mb-4">If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights under the General Data Protection Regulation (GDPR).</p>
                <p className="mb-4">We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
                <p className="mb-4">You have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>The right to access</strong> – You have the right to request copies of your personal data.</li>
                  <li><strong>The right to rectification</strong> – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete information you believe is incomplete.</li>
                  <li><strong>The right to erasure</strong> – You have the right to request that we erase your personal data, under certain conditions.</li>
                  <li><strong>The right to restrict processing</strong> – You have the right to request that we restrict the processing of your personal data, under certain conditions.</li>
                  <li><strong>The right to object to processing</strong> – You have the right to object to our processing of your personal data, under certain conditions.</li>
                  <li><strong>The right to data portability</strong> – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
                </ul>
                <p className="mt-4">To exercise any of these rights, please contact us at info@outercircl.com.</p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section id="us-privacy-laws">
                <h2 className="text-2xl font-semibold mb-4">US State Privacy Rights</h2>
                
                <div className="bg-[#FFEFEF] border-l-4 border-[#E60023] pl-4 py-3 mb-5">
                  <p className="text-sm font-medium">These rights vary by state and are constantly evolving. The information below reflects current requirements as of {new Date().toLocaleDateString()}</p>
                </div>
                
                <h3 className="text-xl font-medium mt-6 mb-3">California Privacy Rights (CCPA/CPRA)</h3>
                <p className="mb-4">Under the California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA), California residents have specific rights regarding their personal information:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Know</strong> - You have the right to request information about personal information collected, disclosed, or sold.</li>
                  <li><strong>Right to Delete</strong> - You have the right to request deletion of personal information we've collected about you.</li>
                  <li><strong>Right to Opt-out of Sale</strong> - You have the right to opt out of the sale of your personal information.</li>
                  <li><strong>Right to Opt-out of Sharing</strong> - You have the right to limit the sharing of your personal information for cross-context behavioral advertising.</li>
                  <li><strong>Right to Limit Use of Sensitive Personal Information</strong> - You have the right to limit certain uses of sensitive personal information.</li>
                  <li><strong>Right to Non-Discrimination</strong> - We will not discriminate against you for exercising your rights.</li>
                  <li><strong>Right to Correction</strong> - You have the right to request correction of inaccurate personal information.</li>
                </ul>
                <p className="mt-4">To make a request under the CCPA/CPRA, please contact us at info@outercircl.com.</p>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Virginia (VCDPA)</h3>
                <p className="mb-4">Under the Virginia Consumer Data Protection Act (VCDPA), Virginia residents have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Access</strong> - You have the right to confirm whether we're processing your personal data and to access such data.</li>
                  <li><strong>Right to Correction</strong> - You have the right to correct inaccuracies in your personal data.</li>
                  <li><strong>Right to Deletion</strong> - You have the right to delete personal data provided by or obtained about you.</li>
                  <li><strong>Right to Data Portability</strong> - You have the right to obtain a copy of your personal data in a portable and usable format.</li>
                  <li><strong>Right to Opt-out</strong> - You have the right to opt out of targeted advertising, the sale of your personal data, and profiling that produces legal or significant effects.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Colorado (CPA)</h3>
                <p className="mb-4">Under the Colorado Privacy Act (CPA), Colorado residents have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Access</strong> - You have the right to confirm whether we're processing your personal data and to access such data.</li>
                  <li><strong>Right to Correction</strong> - You have the right to correct inaccuracies in your personal data.</li>
                  <li><strong>Right to Deletion</strong> - You have the right to delete your personal data.</li>
                  <li><strong>Right to Data Portability</strong> - You have the right to obtain your personal data in a portable and usable format.</li>
                  <li><strong>Right to Opt-out</strong> - You have the right to opt out of targeted advertising, the sale of your personal data, and profiling that produces legal or significant effects.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Connecticut (CTDPA)</h3>
                <p className="mb-4">Under the Connecticut Data Privacy Act (CTDPA), Connecticut residents have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Access</strong> - You have the right to confirm whether we're processing your personal data and to access such data.</li>
                  <li><strong>Right to Correction</strong> - You have the right to correct inaccuracies in your personal data.</li>
                  <li><strong>Right to Deletion</strong> - You have the right to delete personal data provided by or obtained about you.</li>
                  <li><strong>Right to Data Portability</strong> - You have the right to obtain a copy of your personal data in a portable and usable format.</li>
                  <li><strong>Right to Opt-out</strong> - You have the right to opt out of targeted advertising, the sale of your personal data, and profiling that produces legal or significant effects.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Utah (UCPA)</h3>
                <p className="mb-4">Under the Utah Consumer Privacy Act (UCPA), Utah residents have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Access</strong> - You have the right to confirm whether we're processing your personal data and to access such data.</li>
                  <li><strong>Right to Deletion</strong> - You have the right to delete personal data you have provided to us.</li>
                  <li><strong>Right to Data Portability</strong> - You have the right to obtain a copy of your personal data in a portable and usable format.</li>
                  <li><strong>Right to Opt-out</strong> - You have the right to opt out of the processing of your personal data for targeted advertising or the sale of your personal data.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Oregon (ORPA)</h3>
                <p className="mb-4">Under the Oregon Consumer Privacy Act (ORPA), Oregon residents have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Know</strong> - You have the right to know what personal data is being collected about you.</li>
                  <li><strong>Right to Access</strong> - You have the right to access your personal data.</li>
                  <li><strong>Right to Correction</strong> - You have the right to correct inaccurate personal data.</li>
                  <li><strong>Right to Deletion</strong> - You have the right to delete your personal data.</li>
                  <li><strong>Right to Data Portability</strong> - You have the right to obtain your personal data in a portable format.</li>
                  <li><strong>Right to Opt-out</strong> - You have the right to opt out of the processing of your personal data for targeted advertising, the sale of your personal data, and profiling.</li>
                </ul>
                
                <h3 className="text-xl font-medium mt-6 mb-3">Texas (TDPA)</h3>
                <p className="mb-4">Under the Texas Data Privacy Act (TDPA), Texas residents have the following rights:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Right to Access</strong> - You have the right to confirm whether we process your personal data and access such data.</li>
                  <li><strong>Right to Deletion</strong> - You have the right to delete personal data concerning you.</li>
                  <li><strong>Right to Correction</strong> - You have the right to correct inaccurate personal data.</li>
                  <li><strong>Right to Opt-out</strong> - You have the right to opt out of the processing of your personal data for targeted advertising or the sale of your personal data.</li>
                </ul>
                
                <p className="mt-6 text-sm bg-[#FFF8E7] border border-[#FED57B] rounded-lg p-4">
                  <strong>How to Exercise Your State Privacy Rights:</strong> To exercise any of these state-specific rights, please send a request by email to info@outercircl.com with the subject line "State Privacy Rights Request".
                </p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Children's Privacy (COPPA)</h2>
                <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers.</p>
                <p>If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to take necessary action.</p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Cookies and Tracking Technologies</h2>
                <p className="mb-4">We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
                <p className="mb-4">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
                <p className="mb-4">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                
                <div className="bg-[#F7F7F7] p-4 rounded-lg my-4 border border-gray-100">
                  <h3 className="font-medium text-base mb-2">Your Cookie Choices</h3>
                  <p className="text-sm mb-2">
                    Most web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove or reject cookies. Please note that if you choose to remove or reject cookies, this could affect the availability and functionality of our Services.
                  </p>
                  <p className="text-sm">
                    In addition to browser controls, you can exercise choices related to interest-based advertising through industry self-regulation tools such as the Digital Advertising Alliance (DAA), the Network Advertising Initiative (NAI), and the European Interactive Digital Advertising Alliance (EDAA).
                  </p>
                </div>
                
                <div className="bg-[#F7F7F7] p-4 rounded-lg my-4 border border-gray-100">
                  <h3 className="font-medium text-base mb-2">Do Not Track</h3>
                  <p className="text-sm">
                    Some internet browsers have incorporated "Do Not Track" features. Most of these features, when turned on, send a signal or preference to the websites you visit indicating that you do not wish to be tracked. At this time, we do not respond to Do Not Track browser settings or signals.
                  </p>
                </div>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
                <p className="mb-4">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "Last Updated" date at the top of this Privacy Policy.</p>
              </section>
              
              <Separator className="border-[#E60023]/10" />
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
                <p className="mb-4">If you have any questions about this Privacy Policy, please contact us:</p>
                <ul className="list-disc pl-6">
                  <li>By email: info@outercircl.com</li>
                  <li>By visiting the contact page on our website</li>
                </ul>
              </section>
            </div>
            
            <div className="mt-10 pt-6 border-t border-[#E60023]/10">
              <Link to="/terms-of-service" className="flex items-center text-sm text-[#E60023] hover:text-[#C5001F] transition-colors">
                <span>View our Terms of Service</span>
                <ArrowUpRight className="h-4 w-4 ml-1" />
              </Link>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
